extends: ["@commitlint/config-angular"]
rules:
  scope-enum:
    - 2
    - "always"
    - # libs
      - "core"
      - "add"
      - "sub"
      - "eslint"
      - "prettier"
      # apps
      - "server"
